In [1]:
import numpy as np

In [2]:
#thresholds = [1.0, 1.25, 1.5, 2.0, 2.25, 2.5, 3.0, 3.25, 3.5]
thresholds = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5]

In [3]:
denoised_filename = f'./data/denoised_dataS_Cr2_noise=0.1_Tmax=1500_overlap=0.15_dt=1.0_ff=0.2_left_right_threshold=1.0.npy'
noisy_filename = './data/noisy_dataS_Cr2_noise=0.1_Tmax=1500_overlap=0.15_dt=1.0_ff=0.2_left_right.npy'
noisy_dataS = np.load(noisy_filename)
denoised_dataS = np.load(denoised_filename)
denoised_dataS.shape, noisy_dataS.shape

((1500,), (1500,))

In [4]:
# stacked_array = np.empty(2 * len(denoised_dataS), dtype=denoised_dataS.dtype)
# stacked_array[0::2] = denoised_dataS  # Fill even indices with s(t)
# stacked_array[1::2] = noisy_dataS    # Fill odd indices with denoised s(t)

In [5]:
data = []
data.append(noisy_dataS)
for t in thresholds:
    data.append(np.load(f'./data/denoised_dataS_Cr2_noise=0.1_Tmax=1500_overlap=0.15_dt=1.0_ff=0.2_left_right_threshold={t}.npy'))
stacked_array = np.vstack(data)
stacked_array.shape

(7, 1500)

In [6]:
# stacked_array = np.vstack((denoised_dataS, noisy_dataS))

In [7]:
# stacked_array.shape

In [8]:
# stacked_array.T.shape

In [9]:
with open('./data/stacked_noisy_denoised_dataS_Cr2_noise=0.1_Tmax=1500_overlap=0.15_dt=1.0_ff=0.2_left_right.npy', 'wb') as f:
    np.save(f, stacked_array)

In [10]:
noisy_dataS[:10].real

array([ 1.        ,  1.        ,  0.65989756,  0.18240032, -0.10661715,
       -0.39572936, -0.28440449, -0.62644202, -0.15857029, -0.0653439 ])

In [11]:
denoised_dataS[:10].real

array([ 1.        ,  0.91338714,  0.63156422,  0.25966075, -0.08266506,
       -0.33732829, -0.42536857, -0.4382187 , -0.28963981, -0.1504203 ])

In [12]:
stacked_array[:5]

array([[ 1.        +0.j        ,  1.        +0.j        ,
         0.65989756+0.60791245j, ..., -0.03198743-0.00767358j,
        -0.32535822+0.12121509j, -0.07946999-0.06040007j],
       [ 1.        +0.j        ,  0.91338714+0.33306203j,
         0.63156422+0.5439111j , ..., -0.07785212+0.0360738j ,
        -0.31962758-0.02784719j,  0.05650331-0.0648028j ],
       [ 1.        +0.j        ,  0.91338714+0.33306203j,
         0.63156422+0.5439111j , ..., -0.11572751-0.06614306j,
        -0.23713716-0.07332296j,  0.04801674-0.12254868j],
       [ 1.        +0.j        ,  0.91338714+0.33306203j,
         0.63156422+0.5439111j , ..., -0.10028893-0.03039156j,
        -0.15063525-0.14364744j,  0.00634965-0.11297297j],
       [ 1.        +0.j        ,  0.91338714+0.33306203j,
         0.63156422+0.5439111j , ..., -0.13445277-0.0065198j ,
        -0.08780668-0.09666958j,  0.00674568-0.09797583j]])